export const events = {
    onUsernameChange: 'onUsernameChange',
    onAvatarChange: 'onAvatarChange',
    onPause: 'onPause',
    onChangeProgress: 'onChangeProgress',
    chengeStateCarousel: 'chengeStateCarousel',
    chengePage: 'chengePage',
    fillTable: 'fillTable',
    authorized: 'authorized',
    unauthorized: 'unauthorized',
    onNewPassword: 'onNewPassword',
    onCloseModal: 'onCloseModal',
    closeModal: 'mod0',
    openSignIn: 'mod1',
};
