export const events = {
    onEditMessage: 'onEditMessage',
    onDescriptionChange: 'onDescriptionChange',
    onSlugChange: 'onSlugChange',
    onSlug2Change: 'onSlug2Change',
    onCodeChange: 'onCodeChange',
    onBotCodeChange: 'onBotCodeChange',
    onRulesChange: 'onRulesChange',
    onTitleChange: 'onTitleChange',
    onBackgroundChange: 'onBackgroundChange',
    onLogoChange: 'onLogoChange',
    onUsernameChange: 'onUsernameChange',
    onAvatarChange: 'onAvatarChange',
    onPause: 'onPause',
    onChangeProgress: 'onChangeProgress',
    chengeStateCarousel: 'chengeStateCarousel',
    chengePage: 'chengePage',
    fillTable: 'fillTable',
    authorized: 'authorized',
    unauthorized: 'unauthorized',
    onNewPassword: 'onNewPassword',
    onCloseModal: 'onClose_choose-avatar', // Важно
    closeModal: 'mod0',
    openSignIn: 'mod1',
    openSignUp: 'mod2',
};
